# *signup
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
	"name": "Damien",
	"username": "blurrr",
	"email": "blur@example.com",
	"bio":"wohoo!",
	"hobbies": "music",
	"password1": "songnotwo",
	"password2": "songnotwo"
}

###

# *login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
	"username": "blurrr",
	"password": "songnotwo"
}

###

# *get all events-homepage
GET http://localhost:3000

###
# *profilepage
GET http://localhost:3000/profile

###

#*Searching**
# *search by user
GET http://localhost:3000/search?search=alice

###

# *search by event
GET http://localhost:3000/search?search=home

###


# *join event
POST http://localhost:3000/api/users/join/1

###

# *leave event
POST http://localhost:3000/api/users/leave/1

###
# *create event
POST http://localhost:3000/api/events/createEvent
Content-Type: application/json

	{
        "title": "Music Fest",
        "date": "2024-09-05T09:00:00Z",
        "description": "Let's boogie.",
        "category": "Music"
    }

###

# *delete event
DELETE  http://localhost:3000/api/events/delete/8
###

###
GET http://localhost:3000/api/events/1

###
# *get all users(for info-not in use)
GET http://localhost:3000/api/users

###

# *logout
POST http://localhost:3000/api/users/logout


###

#todo
POST http://localhost:3000/api/users/cancel/1

###