# *signup
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
	"username": "blur",
	"email": "blur@example.com",
	"bio":"wohoo!",
	"hobbies": "music",
	"password1": "songnotwo",
	"password2": "songnotwo"
}

###

# *login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
	"username": "blur",
	"password": "songnotwo"
}

###

# *get all events-homepage
GET http://localhost:3000

###

###
GET http://localhost:3000/search?search=alice

# *profilepage-not done
GET http://localhost:3000/api/users/profile

###
GET http://localhost:3000/api/events/1

###
# *get all users(for info-not in use)
GET http://localhost:3000/api/users

###
