GET http://localhost:3000/api/events

###
GET http://localhost:3000/api/events/1

###
GET http://localhost:3000/profile

###
GET http://localhost:3000/friends

###
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
	"username": "trace",
	"email": "trace@example.com",
	"password1": "12345678",
	"password2": "12345678"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
	"username": "trace",
	"password": "12345678"
}